### ISSUE TITLE
Error in VotingContract.new

### ISSUE THREAD

**Issue by afixibiranchi** [llSourcell/Your_First_Decentralized_Application#14]
> deployedContract = VotingContract.new(['Rama','Nick','Jose'],{data: byteCode, from: web3.eth.accounts[0], gas: 4700000})

**Comment by pengyu** [comment]
I also got the same error. Does anybody know how to fix the problem? Thanks.

```
>  deployedContract = VotingContract.new(['Rama','Nick','Jose'],{data: byteCode, from: web3.eth.accounts[0], gas: 4700000})
Error: Invalid JSON RPC response: undefined
    at Object.InvalidResponse (/private/tmp/Your_First_Decentralized_Application/node_modules/web3/lib/web3/errors.js:38:16)
    at HttpProvider.send (/private/tmp/Your_First_Decentralized_Application/node_modules/web3/lib/web3/httpprovider.js:95:18)
    at RequestManager.send (/private/tmp/Your_First_Decentralized_Application/node_modules/web3/lib/web3/requestmanager.js:58:32)
    at Eth.get [as accounts] (/private/tmp/Your_First_Decentralized_Application/node_modules/web3/lib/web3/property.js:107:62)
    at repl:1:94
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
```
