### ISSUE TITLE
web3.eth.accounts will result to Error: Invalid JSON RPC response

### ISSUE THREAD

**Issue by hendrawd** [llSourcell/Your_First_Decentralized_Application#17]
Here is the complete error stack trace:

```
> web3.eth.accounts
Error: Invalid JSON RPC response: undefined
    at Object.InvalidResponse (/Users/hendrawd/version-control/Your_First_Decentralized_Application/node_modules/web3/lib/web3/errors.js:38:16)
    at HttpProvider.send (/Users/hendrawd/version-control/Your_First_Decentralized_Application/node_modules/web3/lib/web3/httpprovider.js:95:18)
    at RequestManager.send (/Users/hendrawd/version-control/Your_First_Decentralized_Application/node_modules/web3/lib/web3/requestmanager.js:58:32)
    at Eth.get [as accounts] (/Users/hendrawd/version-control/Your_First_Decentralized_Application/node_modules/web3/lib/web3/property.js:107:62)
    at repl:1:9
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
```

**Comment by timB73** [comment]
I got same issue, no idea what to do :(

**Comment by hendrawd** [comment]
@Z-Neutrino Sorry I can't help, since I also haven't resolved it yet.

**Comment by b232wang** [comment]
same issue, no idea what to do :(
